version: '3'

services:
  api-server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: api-server
    command: yarn dev
    environment:
      - DB_HOST=api-postgres
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=data
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - api-postgres
    networks:
      - backend-network
  api-postgres:
    image: bitnami/postgresql:latest
    container_name: api-postgres
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=data
    ports:
      - 5432:5432
    volumes:
      - api-postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  api-postgres-data:
networks:
  backend-network:
    driver: bridge
